SELECT SYSDATE,
ADD_MONTHS(SYSDATE, 1) as ADD_MONTH_RESULT
FROM dual;

SELECT SYSDATE,
ADD_MONTHS(SYSDATE, 6) as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE,
ADD_MONTHS(SYSDATE, 41) as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE, ADD_MONTHS(SYSDATE, -6) as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE, ADD_MONTHS(SYSDATE, '5') as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE, ADD_MONTHS(SYSDATE, 'Six') as ADD_MONTH_RESULT
FROM dual;

SELECT TO_DATE('08-JUL-2015') as INPUT_DATE,
ADD_MONTHS(TO_DATE('08-JUL-2015'), 1) as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE, 
ADD_MONTHS(SYSDATE, 2.3) as ADD_MONTH_RESULT_LOW,
ADD_MONTHS(SYSDATE, 2.9) as ADD_MONTH_RESULT_HIGH
FROM dual;


SELECT SYSDATE, ADD_MONTHS(SYSDATE, 12) as ADD_MONTH_RESULT
FROM dual;


SELECT SYSDATE,
TRUNC(ADD_MONTHS(LAST_DAY(SYSDATE)+1,-1)) as FIRST_DAY
FROM dual;

