SELECT TO_DATE('01-JNA-2015') FROM dual;


SELECT TO_DATE('14-APR-2015', 'DD-MON-YYYY') FROM dual;

--Change NLS_DATE_FORMAT
SELECT * FROM nls_session_parameters WHERE parameter = 'NLS_DATE_LANGUAGE';

SELECT * FROM nls_session_parameters WHERE parameter = 'NLS_DATE_FORMAT';

SELECT TO_DATE('22/MAY/2015') FROM dual;

ALTER SESSION SET NLS_DATE_FORMAT = 'MM-DD-YYYY';

SELECT TO_DATE('22/MAY/2015') FROM dual;

SELECT TO_DATE('05-22-2015') FROM dual;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MON/RR';
SELECT * FROM nls_session_parameters WHERE parameter = 'NLS_DATE_FORMAT';